volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    container_name: foodgram-db
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: maximylis/foodgram-backend:latest
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate --noinput &&
            python manage.py load_ingredients &&
            python manage.py load_tags &&
            python manage.py collectstatic --noinput &&
            cp -r /app/static/. /backend_static/static/ &&
            gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    container_name: foodgram-frontend
    image: maximylis/foodgram-frontend:latest
    volumes:
      - frontend_build:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: maximylis/foodgram-gateway:latest
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html/
      - static:/backend_static
      - media:/app/media
    depends_on:
      - backend
      - frontend
